### ISSUE TITLE
Error creating session dial udp xx.xx.xx.xx:53: socket: too many open files

### ISSUE THREAD

**Issue by jamie1911** [yyyar/gobetween#152]
I'm having some difficulty setting up gobetween to load balance DNS traffic between two backend DNS servers.

I keep getting "Error creating session dial udp xx.xx.xx.xx:53: socket: too many open files" whenever we start to receive high volume to DNS lookups. 

I have configured the timeout values to the low 2 seconds which seem to help. However, it still occurs from time to time and stops responding. Any advice would be appreciated and I can provide any additional information to help troubleshoot. 

The current config is as such:

```
[defaults]
max_connections = 0              # Maximum simultaneous connections to the server
client_idle_timeout = "5s"        # Client inactivity duration before forced connection drop
backend_idle_timeout = "2s"       # Backend inactivity duration before forced connection drop
backend_connection_timeout = "2s" # Backend connection timeout (ignored in udp)
balance = "roundrobin"
#
# Servers contains as many [server.<name>] sections as needed.
#
[servers]
# ---------- tcp ----------- #
[servers.dnsTCP]
protocol = "tcp"
bind = "0.0.0.0:53"

  [servers.dnsTCP.discovery]
  kind = "static"
  static_list = [
      "10.0.0.201:53 weight=5",
      "10.0.0.202:53 weight=5"
  ]
# ---------- udp ----------- #
[servers.dnsUDP]
bind = "0.0.0.0:53"
protocol = "udp"

  [servers.dnsUDP.udp]
  max_responses = 0
  max_requests = 2

  [servers.dnsUDP.discovery]
  kind = "static"
  static_list = [
      "10.0.0.201:53 weight=5",
      "10.0.0.202:53 weight=5"
  ]
```

**Comment by nickdoikov** [comment]
Hello @jamie1911  your problem is clear , you should run gobetween with defining appropriate limits according to your needs 
for example you need 40K connections , so you should open ~80K descriptors for this.

try run gb this way( please change path to your`s) : 
```
bash -c ulimit -n 80000; /usr/local/bin/gobetween -c /etc/gobetween.toml
```

also you can check current limits by :
```
#cat /proc/$(pidof gobetween)/limits
```
and you can check currently opened by GB descriptors:
```
ls -l /proc/$(pidof gobetween)/fd | wc -l
```

**Comment by jamie1911** [comment]
Thanks for the information as I think this will also allow us to increase the traffic here.

I do have a few questions as I was able to reproduce the error quite frequently and found that changing 

`  [servers.dnsUDP.udp]
  max_responses = 0
  max_requests = 2`

to

`  [servers.dnsUDP.udp]
  max_responses = 1
  max_requests = 0
`

Changing the max_responses = 1, seems to resolve the issue I was having.. can you give a little more information about what happens behind the scenes with this? From what I can gather, it tells gobetween to accept one response session from the backend server and then disconnect the session? 

I was able to see this in action by watching the open connections to the backend using netstat:
`watch -n 1 'netstat -an|grep "53        ESTABLISHED" | wc -l'`

This now stays in the low teens, instead of the thousands as before.

**Comment by illarion** [comment]
@jamie1911 UDP is a session-less protocol, so gobetween has to track relation between client sending packets via gobetween to the backend and responses being issued by backend, in order to send them to the appropriate client. This relation is a "session". There is no way to close this session intentionally from client or server, so we have to add metrics: `max_responses` - close session after this number of response packets, `max_requests` - close session after this number of requests, or timeouts: `client_idle_timeout` and `backend_idle_timeout`

**Comment by illarion** [comment]
@jamie1911 dns protocol has only one response packet from server, that is why setting max_responses to 1 did the trick - gobetween closes the socket after first response.

**Comment by jamie1911** [comment]
Thanks, these responses sum it up  for me
@nickdoikov 
@illarion
