### ISSUE TITLE
[feature request] Layer7 Support (HTTP)

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#157]
Hi,

Would it be possible to implement support for "http" mode?
I have been able to live with TCP+SNI till now, but now I have a need for HTTP(S) as well.

I have started using Fabio for now, but the Gobetween "usability simplicity" has me "hooked" 😀 .
(I also tried Traefik, but Traefik does L7 only(

With that said, I would like to submit a feature request for this.
Hope you guys consider this.

Thanks and Regards for an awesome product,
Shantanu.

BTW, Traefik also uses .toml syntax, so there is quite a bit of .toml familiarity among users
I think if Gobetween were able to do L7 as well, it would awesome. 🥇

**Comment by shantanugadgil** [comment]
<bump> any thoughts on this? @yyyar @nickdoikov @illarion

**Comment by hampsterx** [comment]
even just some basic support would be great. (only just found this project 15m ago) seems like currently if you want to use gobtween for service discovery you are forced to assign a port to each service rather than a route? would be nice to have prod.internal/my-service/ for example. We are currently using consul DNS but finding it would be easier to not have to deal with the complexity of SRV records in our apps.

**Comment by shantanugadgil** [comment]
closing due to age
