### ISSUE TITLE
[feature request] enable basic_auth for tls

### ISSUE THREAD

**Issue by shantanugadgil** [yyyar/gobetween#189]
I would like to propose the `basic_auth` section for `tls` type of connection.
(Similar to what is present for the REST API block)

_Thus by extension, can it be done for `tcp` as well? (though not my requirement)_

My  use case is that I would like to provide an "SSL + password" functionality to browse Consul (and/or Nomad) and not expose the actual non SSL ports.

Doing it using various other tools like HAProxy, NGINX, Stunnel is certainly possible, but a bit tedious. 

Thanks and Regards,
Shantanu

**Comment by illarion** [comment]
@shantanugadgil gobetween is the L4 balancer. Basic Auth is the feature of http protocol. In order to require user to authenticate, server should answer with specific status code, headers etc. It is easy to implement in http API endpoint, like our rest api, but not possible for plain TCP or TLS. Gobetween actually is not aware what protocol backends are implementing, and in very many use cases it is not HTTP

**Comment by illarion** [comment]
This feature request is one small use case of L7 support in general. L7 is not planned in v0.x versions of gobetween and not yet decided what version will support it v1.x or v2.x, so it's not for now, sorry.
