### ISSUE TITLE
v0.6.1 - UDP requests not being logged in debug mode

### ISSUE THREAD

**Issue by Novanet-** [yyyar/gobetween#202]
Hi.

I just tried upgrading gobetween for v0.5 to v0.6.1, and now the debug statements that appear whenever a UDP request is made to the load balancer, do not appear anymore. Looking at the API I've confirmed the requests are still getting load balanced, but the console isn't printing the debug statements anymore.

**gobetween.json (same on both versions)**
https://pastebin.com/kmgnEKzK

**v0.5 console**
![2019-03-07 17_39_09-v-wdavi4 on c-wdavi - virtual machine connection](https://user-images.githubusercontent.com/6632123/53978795-002af280-4104-11e9-9179-6d9e4e89638f.png)

**v0.6.1 console**
![2019-03-07 18_05_26-v-wdavi4 on c-wdavi - virtual machine connection](https://user-images.githubusercontent.com/6632123/53978809-07ea9700-4104-11e9-93b8-7045191b6aad.png)

**Stats (same on both versions)**
![2019-03-07 18_06_01-mozilla firefox](https://user-images.githubusercontent.com/6632123/53979078-b42c7d80-4104-11e9-8dbb-822205dcef38.png)

**Comment by cunningwasabi** [comment]
how big a deal is this for you? It's pretty straight forward to do...

**Comment by Novanet-** [comment]
Well it's a regression from previous behaviour, and we were using it to quickly see if the load balancing was working as intended.

**Comment by illarion** [comment]
@Novanet-  logging in such a critical place causes performance degradation and was removed during work on udp speedup. Unfortunately golang has no macros support to eliminate string evaluation for disabled loglevels.

**Comment by illarion** [comment]
Closing it for now. Detailed logging will be added if we will find solution for zero-cost logging of only enabled loglevels

**Comment by cunningwasabi** [comment]
My 2c because debug logging is critical for any project like this..

An option for zero-cost debug logs is to wrap a debug function and using compile options.
https://stackoverflow.com/questions/36703867/golang-preprocessor-like-c-style-compile-switch
we just make a debug() function that is only included for go compiles with the DEBUGGING compile time option.
eg; go build -tags "DEBUGGING"

to make it work, we need two new files;
**logging/log_debug_off.go**
```
// this code included only if the DEBUGGING tag is NOT specified for building
// +build !DEBUGGING

func Debug(x string) {
// nop
}
```

**logging/log_debug_on.go**
```
// the code included only if the DEBUGGING tag is specified for building
// +build DEBUGGING

func Debug(x string) {
log.debug(x)
}
```

for distribution purposes, if you wanted to give people the option you could build a "gobetween" and a "gobetween-debug" and ship that.
