### ISSUE TITLE
Persisting source address

### ISSUE THREAD

**Issue by z0lt3c** [yyyar/gobetween#203]
I know this has come up in a few prior issues already, but I also need the ability to the persist the source address for UDP packets.  Has this feature been committed to a release yet?

**Comment by cunningwasabi** [comment]
do you mean the "sticky sessions" concept? where the backend for a particular client IP remains consistently over a defined UDP lifetime?

**Comment by z0lt3c** [comment]
No, I mean that when you forward a UDP packet to the backend, you persist the original source address and do not change the source address to the VIP.  For nginx, you can achieve this with: "proxy_bind $remote_addr transparent;"

**Comment by eric-lindau** [comment]
I'm working on something for this, but I've gone down the rabbit hole and found that with Go this is harder than it sounds.

The only ways I see possible to do this are
1. Writing custom packets to the wire (which requires writing custom frames)
2. Using raw IP sockets (POSIX) to circumvent the kernel from writing its own IP headers (which doesn't require any customization with Layer 2)

I believe option 2 is easier and would lead to fewer issues.
I'm hoping to get [this repo](https://github.com/eric-lindau/udpfacade/blob/master/udp.go) to the point of reliability I want. There are just a few catches...
- Raw sockets require elevated privileges
- The Go networking library abstracts the network away enough to where gobetween's current [UDP functionality](https://github.com/eric-lindau/udpfacade/blob/master/udp.go) would require significant change to support this, as raw sockets are below Go's scope

I hope to get that repo to a level of abstraction similar to Go's UDP interface so that this wouldn't be too difficult. Unless anyone else knows of an easier way to do this, I will probably continue on this path.

**Comment by illarion** [comment]
@nuttysquirrel persistent connections are already implemented, see project wiki about udp regarding virtual sessions.
 
@z0lt3c, I've just merged PR (many thanks to @eric-lindau ) that implements transparent udp, so that packets from client to the backend go via gobetween, but any packets in response (if any) are transfered directly to the client, because source address (host and port) are not modified.

Thank you all for great contribution!
