### ISSUE TITLE
Errata/bug

### ISSUE THREAD

**Issue by trueblacker** [yyyar/gobetween#42]
I believe there must be "+=" [here](https://github.com/yyyar/gobetween/blob/e70b7e7cd899b9e12214a504407be68505765567/src/server/proxy.go#L75)

**Comment by yyyar** [comment]
Yep :-) The funny part is that seems it does not affect resulting stats calculations because we really count only written bytes [here] (https://github.com/yyyar/gobetween/blob/e70b7e7cd899b9e12214a504407be68505765567/src/server/server.go#L270) and [here](https://github.com/yyyar/gobetween/blob/e70b7e7cd899b9e12214a504407be68505765567/src/server/server.go#L273) from backend to client and vice-versa. Need to check more carefully, though.

But taking closer look at the code around it seems for me that 1) we can optimize by removing CountRead calculations at all, and 2) need check if [this](https://github.com/yyyar/gobetween/blob/e70b7e7cd899b9e12214a504407be68505765567/src/server/proxy.go#L66) is right and not messed up.

@trueblacker thanks for pointing it out!

**Comment by trueblacker** [comment]
I can say that for my particular task read statistics was exactly the thing I needed, though it took some time to bring it to output & fix that issue by myself.
So, don't remove that, you never know what you need tomorrow :-)

And thanks for the great job too. A pretty impressive tool you've got here.

**Comment by illarion** [comment]
@trueblacker could you please share with us what was your particular task and how did you solve it? Thank you.

**Comment by illarion** [comment]
Fixed in #43

**Comment by trueblacker** [comment]
Haven't solved yet. Trying to find out which side looses network packets on high load. As for now the idea is to place gobetween between the peers and watch them read & write the data, comparing the inbound and outbound numbers for proxy connections.

**Comment by illarion** [comment]
@trueblacker TCP handles packet loss by itself, so that you'll not see any, since lost packets will be resent, or if it is not possible connection will be dropped. How do you expect gobetween help you to detect problems?

**Comment by trueblacker** [comment]
I hope the problem is above TCP level and the question is just which side is guilty on what - not sending all the data necessary or not reading the all data from the socket

**Comment by illarion** [comment]
@trueblacker anyway we've fixed errata in #43 so that feel free to update.

**Comment by trueblacker** [comment]
ok, thanx
