### ISSUE TITLE
RoundRobin balancing not working

### ISSUE THREAD

**Issue by rafaelcarsetimo** [yyyar/gobetween#79]
I made a RoudRobin balancngo as above:

## SyslogUDPWindowsDefault ##
[servers.nodeudp13514]
bind = "192.168.0.200:13514"
protocol = "udp"
balance = "roundrobin"

  [servers.nodeudp13514.udp]
  max_responses = 0

  [servers.nodeudp13514.discovery]
  kind = "static"
  static_list = [
      "node1.domain.com:13514",
      "node2.domain.com:13514",
      "node3.domain.com:13514"
  ]

The node1 and node2 receives the balance, but node 3 dont.
I Try weight, but not success.

**Comment by illarion** [comment]
Looks like you have 2 producers and 3 consumers, so that traffic is routed to only node1 and node2. 

If you want to send traffic to all nodes, please specify max_responses > 0, so that gb will drop the virtual connection between source host:port and destination (backend) host:port and route traffic to the next node after first answer.

If backends work in strict consumer mode without any responses, then you can specify backend_idle_timeout so that traffic will get rebalanced periodically

**Comment by illarion** [comment]
#80

**Comment by rafaelcarsetimo** [comment]
Thanks! Works! Sorry...

**Comment by illarion** [comment]
@rafaelcarsetimo I've added option max_requests to udp section. It will be available in the next release
